### ISSUE TITLE
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found, Can anyone help me? Thank you~

### ISSUE THREAD

**Issue by liaochangjian** [google-research/mood-board-search#12]
Hi!

When I run python3.8 bin/download_data.py, but I get this error.
My system is CentOS 7 
Can anyone help me please?

`/usr/local/python3Dir/bin/python3.8 bin/download_data.py
Traceback (most recent call last):
  File "bin/download_data.py", line 37, in <module>
    from cavstudio_backend.image_reference import precalculate_activations, ImageReference
  File "/opt/mood-board-search-main/backend/cavstudio_backend/image_reference.py", line 27, in <module>
    from .ml_engine import MODEL_LAYERS, ml_engine
  File "/opt/mood-board-search-main/backend/cavstudio_backend/ml_engine.py", line 23, in <module>
    from cavlib.models import GooglenetModel, MobilenetModel, Model
  File "/opt/mood-board-search-main/cavlib/src/cavlib/__init__.py", line 15, in <module>
    from cavlib.activations import compute_activations, CAVableImage
  File "/opt/mood-board-search-main/cavlib/src/cavlib/activations.py", line 23, in <module>
    import skimage.transform
  File "/usr/local/python3Dir/lib/python3.8/site-packages/skimage/transform/__init__.py", line 1, in <module>
    from .histogram_matching import match_histograms
  File "/usr/local/python3Dir/lib/python3.8/site-packages/skimage/transform/histogram_matching.py", line 3, in <module>
    from ..exposure import match_histograms as mh
  File "/usr/local/python3Dir/lib/python3.8/site-packages/skimage/exposure/__init__.py", line 1, in <module>
    from .exposure import histogram, equalize_hist, \
  File "/usr/local/python3Dir/lib/python3.8/site-packages/skimage/exposure/exposure.py", line 3, in <module>
    from ..color import rgb2gray
  File "/usr/local/python3Dir/lib/python3.8/site-packages/skimage/color/__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "/usr/local/python3Dir/lib/python3.8/site-packages/skimage/color/colorconv.py", line 55, in <module>
    from scipy import linalg
  File "/usr/local/python3Dir/lib/python3.8/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/usr/local/python3Dir/lib/python3.8/site-packages/scipy/fft/__init__.py", line 76, in <module>
    from ._basic import (
  File "/usr/local/python3Dir/lib/python3.8/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/usr/local/python3Dir/lib/python3.8/site-packages/scipy/_lib/uarray.py", line 27, in <module>
    from ._uarray import *
  File "/usr/local/python3Dir/lib/python3.8/site-packages/scipy/_lib/_uarray/__init__.py", line 114, in <module>
    from ._backend import *
  File "/usr/local/python3Dir/lib/python3.8/site-packages/scipy/_lib/_uarray/_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /lib64/libstdc++.so.6)`

**Comment by liaochangjian** [comment]
https://blog.csdn.net/m0_46093414/article/details/121009113

fix it
