### ISSUE TITLE
Error running pip install -r requirements.txt

### ISSUE THREAD

**Issue by jamesgrubb** [google-research/mood-board-search#4]
Obtaining file:///../cavlib (from -r requirements.txt (line 7))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting appnope==0.1.0
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting asgiref==3.4.1
  Using cached asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting backcall==0.1.0
  Using cached backcall-0.1.0.zip (11 kB)
  Preparing metadata (setup.py) ... done
Collecting cached-property==1.5.1
  Using cached cached_property-1.5.1-py2.py3-none-any.whl (6.0 kB)
Collecting click==7.0
  Using cached Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting decorator==4.4.1
  Using cached decorator-4.4.1-py2.py3-none-any.whl (9.2 kB)
Collecting django==3.2.8
  Using cached Django-3.2.8-py3-none-any.whl (7.9 MB)
Collecting django-cors-headers==3.2.1
  Using cached django_cors_headers-3.2.1-py3-none-any.whl (14 kB)
Collecting django-rest-framework==0.1.0
  Using cached django-rest-framework-0.1.0.tar.gz (969 bytes)
  Preparing metadata (setup.py) ... done
Collecting djangorestframework==3.11.0
  Using cached djangorestframework-3.11.0-py3-none-any.whl (911 kB)
Collecting entrypoints==0.3
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting flake8==3.7.9
  Using cached flake8-3.7.9-py2.py3-none-any.whl (69 kB)
Collecting gunicorn[gthread]==20.0.4
  Using cached gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
Collecting imageio==2.8.0
  Using cached imageio-2.8.0-py3-none-any.whl (3.3 MB)
Collecting ipython==7.12.0
  Using cached ipython-7.12.0-py3-none-any.whl (777 kB)
Collecting ipython-genutils==0.2.0
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jedi==0.16.0
  Using cached jedi-0.16.0-py2.py3-none-any.whl (1.1 MB)
Collecting joblib==0.14.1
  Using cached joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting kiwisolver==1.1.0
  Using cached kiwisolver-1.1.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib==3.1.3
  Using cached matplotlib-3.1.3.tar.gz (40.9 MB)
  Preparing metadata (setup.py) ... done
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting methodtools==0.1.2
  Using cached methodtools-0.1.2.tar.gz (2.7 kB)
  Preparing metadata (setup.py) ... done
Collecting msgpack==1.0.0
  Using cached msgpack-1.0.0.tar.gz (232 kB)
  Preparing metadata (setup.py) ... done
Collecting networkx==2.4
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting numpy==1.18.1
  Using cached numpy-1.18.1.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [237 lines of output]
      Running from numpy source directory.
      setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      /private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bit_generator.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      accelerate_info:
        libraries accelerate not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
      Library accelerate was not found. Ignoring
        libraries veclib not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
      Library veclib was not found. Ignoring
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      svnversion: error: The subversion command line tools are no longer provided by Xcode.
      non-existing path in 'numpy/distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries tatlas,tatlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries tatlas,tatlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries tatlas,tatlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries satlas,satlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries satlas,satlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries satlas,satlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries ptf77blas,ptcblas,atlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries f77blas,cblas,atlas not found in /Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries f77blas,cblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries f77blas,cblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      /private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build/src.macosx-10.9-universal2-3.10
      creating build/src.macosx-10.9-universal2-3.10/numpy
      creating build/src.macosx-10.9-universal2-3.10/numpy/distutils
      building library "npymath" sources
      Could not locate executable gfortran
      Could not locate executable f95
      Could not locate executable f90
      Could not locate executable f77
      Could not locate executable xlf90
      Could not locate executable xlf
      Could not locate executable ifort
      Could not locate executable ifc
      Could not locate executable g77
      Could not locate executable g95
      Could not locate executable pgfortran
      don't know how to compile Fortran code on platform 'posix'
      creating build/src.macosx-10.9-universal2-3.10/numpy/core
      creating build/src.macosx-10.9-universal2-3.10/numpy/core/src
      creating build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/npy_math_internal.h
        adding 'build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath' to include_dirs.
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/ieee754.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/npy_math_complex.c
      None - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath/npy_math_internal.h']
      building library "npysort" sources
      creating build/src.macosx-10.9-universal2-3.10/numpy/core/src/common
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/common/npy_sort.h
        adding 'build/src.macosx-10.9-universal2-3.10/numpy/core/src/common' to include_dirs.
      creating build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/quicksort.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/mergesort.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/timsort.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/heapsort.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/radixsort.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/common/npy_partition.h
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/selection.c
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/common/npy_binsearch.h
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/npysort/binsearch.c
      None - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.10/numpy/core/src/common/npy_sort.h', 'build/src.macosx-10.9-universal2-3.10/numpy/core/src/common/npy_partition.h', 'build/src.macosx-10.9-universal2-3.10/numpy/core/src/common/npy_binsearch.h']
      building extension "numpy.core._multiarray_tests" sources
      creating build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray
      conv_template:> build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/_multiarray_tests.c
      building extension "numpy.core._multiarray_umath" sources
      Traceback (most recent call last):
        File "/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/jamesgrubb/Dropbox/Dev/mood-board-search/backend/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 488, in <module>
          setup_package()
        File "setup.py", line 480, in setup_package
          setup(**metadata)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/numpy/distutils/core.py", line 171, in setup
          return old_setup(**new_attr)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 35, in run
          egg_info.run()
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/numpy/distutils/command/egg_info.py", line 26, in run
          self.run_command("build_src")
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-build-env-v94usc7i/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/numpy/distutils/command/build_src.py", line 146, in run
          self.build_sources()
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/numpy/distutils/command/build_src.py", line 163, in build_sources
          self.build_extension_sources(ext)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/numpy/distutils/command/build_src.py", line 320, in build_extension_sources
          sources = self.generate_sources(sources, ext)
        File "/private/var/folders/vg/48dgq5bd3zb_6fgltlckz6j00000gn/T/pip-install-wkdrb8r6/numpy_116b2c98dcc7459dbe01ba9080a80d42/numpy/distutils/command/build_src.py", line 380, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 430, in generate_config_h
          moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
        File "numpy/core/setup.py", line 49, in check_types
          out = check_types(*a, **kw)
        File "numpy/core/setup.py", line 286, in check_types
          raise SystemError(
      SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
➜  backend git:(main)

**Comment by joerick** [comment]
Hi @jamesgrubb. It looks like maybe you're installing into a Python 3.10 venv? The project dependencies are pinned for Python 3.8.

**Comment by jamesgrubb** [comment]
That fixed it thank you
