### ISSUE TITLE
ValidationError: Progress Plugin Invalid Options

### ISSUE THREAD

**Issue by SmartIJD** [google-research/mood-board-search#6]
Hi, after executing the last command, "npm run serve," I saw the following information and error. Any suggestions for solving the problem will be very appreciated. I am running this project on a Mac (12.6) with Python (3.8.6) and Node (v15.14.0 & v16.16.0). Thank you so much.
`
> cavstudio@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  ValidationError: Progress Plugin Invalid Options
        
        options should NOT have additional properties
        options should NOT have additional properties
        options should NOT have additional properties
        options should pass "instanceof" keyword validation
        options should match exactly one schema in oneOf
        
ValidationError: Progress Plugin Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (/Users/.../Moodboard-search/frontend/node_modules/webpack/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new ProgressPlugin (/Users/.../Moodboard-search/frontend/node_modules/webpack/lib/ProgressPlugin.js:62:3)
    at new Progress (/Users/.../Moodboard-search/frontend/node_modules/progress-webpack-plugin/index.js:25:21)
    at new progressPlugin (/Users/.../Moodboard-search/frontend/node_modules/progress-webpack-plugin/index.js:127:10)
    at /Users/.../Moodboard-search/frontend/node_modules/webpack-chain/src/Plugin.js:14:18
    at Object.toConfig (/Users/.../Moodboard-search/frontend/node_modules/webpack-chain/src/Plugin.js:78:22)
    at /Users/.../Moodboard-search/frontend/node_modules/webpack-chain/src/Config.js:129:63
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/.../Moodboard-search/frontend/node_modules/webpack-chain/src/Config.js:129:40)
    at Service.resolveWebpackConfig (/Users/.../Moodboard-search/frontend/node_modules/@vue/cli-service/lib/Service.js:277:34)
`

**Comment by joerick** [comment]
did you do `npm install` or `npm ci`? This looks like a dependency problem, so `npm ci` is much more likely to work.

**Comment by SmartIJD** [comment]
>@joerick

I followed the instruction and used "npm ci." At that time, I saw the following "warns" and applied "npm audit fix" to fix some of them. Do you have any other suggestions? Thanks.

`(env) yaliang@MacBooko17OS121 frontend % npm ci
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated vue-context@5.0.0: No longer maintained
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.11: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1342 packages, and audited 1343 packages in 17s

106 packages are looking for funding
  run `npm fund` for details

8 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.`
